name="Wild Duck Mail Temporary"

[service]
    # email domain for new users
    domain="local.tahvel.info"
    # default quotas for new users
    quota=102400
    # allowed domains for new addresses
    domains=["local.tahvel.info", "example.com"]

[www]
    proxy=true
    baseurl="https://local.tahvel.info"
    port=5000

[setup]
    # these values are shown in the configuration help page
    [setup.imap]
        hostname="local.tahvel.info"
        secure=true
        port=993
    [setup.pop3]
        hostname="local.tahvel.info"
        secure=true
        port=995
    [setup.smtp]
        hostname="local.tahvel.info"
        secure=false
        port=587
